export const properties = [
  {
    id: 1,
    image: "/commercial/commercial-house.png",
    price: "৳48,000,000",
    type: "Apartment",
    location: "Gulshan 2, Dhaka",
    beds: 4,
    baths: 3,
    sqft: 2370,
    isVerified: true,
    forSale: true,
  },
  {
    id: 2,
    image: "/commercial/commercial-house.png",
    price: "৳35,000,000",
    type: "Duplex",
    location: "Banani, Dhaka",
    beds: 5,
    baths: 4,
    sqft: 3200,
    isVerified: false,
    forSale: true,
  },
  {
    id: 3,
    image: "/commercial/commercial-house.png",
    price: "৳22,500,000",
    type: "Condo",
    location: "Dhanmondi, Dhaka",
    beds: 3,
    baths: 3,
    sqft: 1800,
    isVerified: true,
    forSale: true,
  },
  {
    id: 4,
    image: "/commercial/commercial-house.png",
    price: "৳18,000,000",
    type: "Apartment",
    location: "Bashundhara, Dhaka",
    beds: 3,
    baths: 2,
    sqft: 1600,
    isVerified: false,
    forSale: true,
  },
  {
    id: 5,
    image: "/commercial/commercial-house.png",
    price: "৳28,500,000",
    type: "Penthouse",
    location: "Baridhara, Dhaka",
    beds: 4,
    baths: 4,
    sqft: 2800,
    isVerified: true,
    forSale: true,
  },
  {
    id: 6,
    image: "/commercial/commercial-house.png",
    price: "৳12,000,000",
    type: "Apartment",
    location: "Mirpur, Dhaka",
    beds: 2,
    baths: 2,
    sqft: 1200,
    isVerified: false,
    forSale: true,
  },
  {
    id: 7,
    image: "/commercial/commercial-house.png",
    price: "৳55,000,000",
    type: "Villa",
    location: "Uttara, Dhaka",
    beds: 6,
    baths: 5,
    sqft: 4500,
    isVerified: true,
    forSale: true,
  },
  {
    id: 8,
    image: "/commercial/commercial-house.png",
    price: "৳30,000,000",
    type: "Duplex",
    location: "Mohakhali DOHS, Dhaka",
    beds: 5,
    baths: 4,
    sqft: 3100,
    isVerified: true,
    forSale: true,
  },
  {
    id: 9,
    image: "/commercial/commercial-house.png",
    price: "৳14,800,000",
    type: "Apartment",
    location: "Khilgaon, Dhaka",
    beds: 3,
    baths: 2,
    sqft: 1450,
    isVerified: false,
    forSale: true,
  },
  {
    id: 10,
    image: "/commercial/commercial-house.png",
    price: "৳25,000,000",
    type: "Condo",
    location: "Shyamoli, Dhaka",
    beds: 4,
    baths: 3,
    sqft: 2200,
    isVerified: true,
    forSale: true,
  },
  {
    id: 11,
    image: "/commercial/commercial-house.png",
    price: "৳19,500,000",
    type: "Apartment",
    location: "Motijheel, Dhaka",
    beds: 3,
    baths: 2,
    sqft: 1750,
    isVerified: false,
    forSale: true,
  },
  {
    id: 12,
    image: "/commercial/commercial-house.png",
    price: "৳65,000,000",
    type: "Penthouse",
    location: "Gulshan 1, Dhaka",
    beds: 5,
    baths: 5,
    sqft: 4800,
    isVerified: true,
    forSale: true,
  },
  {
    id: 13,
    image: "/commercial/commercial-house.png",
    price: "৳17,000,000",
    type: "Apartment",
    location: "Malibagh, Dhaka",
    beds: 3,
    baths: 2,
    sqft: 1500,
    isVerified: false,
    forSale: true,
  },
  {
    id: 14,
    image: "/commercial/commercial-house.png",
    price: "৳20,000,000",
    type: "Condo",
    location: "Rampura, Dhaka",
    beds: 3,
    baths: 3,
    sqft: 1850,
    isVerified: true,
    forSale: true,
  },
  {
    id: 15,
    image: "/commercial/commercial-house.png",
    price: "৳42,000,000",
    type: "Villa",
    location: "Baridhara DOHS, Dhaka",
    beds: 6,
    baths: 5,
    sqft: 4200,
    isVerified: true,
    forSale: true,
  },
  {
    id: 16,
    image: "/commercial/commercial-house.png",
    price: "৳27,000,000",
    type: "Duplex",
    location: "Mohammadpur, Dhaka",
    beds: 4,
    baths: 3,
    sqft: 2500,
    isVerified: false,
    forSale: true,
  },
  {
    id: 17,
    image: "/commercial/commercial-house.png",
    price: "৳15,000,000",
    type: "Apartment",
    location: "Kazipara, Mirpur",
    beds: 3,
    baths: 2,
    sqft: 1400,
    isVerified: false,
    forSale: true,
  },
  {
    id: 18,
    image: "/commercial/commercial-house.png",
    price: "৳32,000,000",
    type: "Condo",
    location: "Paltan, Dhaka",
    beds: 4,
    baths: 3,
    sqft: 2700,
    isVerified: true,
    forSale: true,
  },
  {
    id: 19,
    image: "/commercial/commercial-house.png",
    price: "৳38,500,000",
    type: "Penthouse",
    location: "Tejgaon, Dhaka",
    beds: 4,
    baths: 4,
    sqft: 3000,
    isVerified: true,
    forSale: true,
  },
  {
    id: 20,
    image: "/commercial/commercial-house.png",
    price: "৳13,500,000",
    type: "Apartment",
    location: "Jatrabari, Dhaka",
    beds: 2,
    baths: 2,
    sqft: 1250,
    isVerified: false,
    forSale: true,
  },
];
